### ISSUE TITLE
Show more button displaying at wrong time.

### ISSUE THREAD

**Issue by mauiflipper** [stakbit/jQuery-Mobile-Listview-Pagination-Plugin#4]
When the Total Found Count is less than the perPage value, the "show more" button is displayed

**Comment by mauiflipper** [comment]
I realize now ths is related to the null issue, based on what u said about returning the total number of found records. So, fixing the null issue will fix this issue.

**Comment by mauiflipper** [comment]
Actually I think fixing the first item in this thread would also fix the issue.

**Comment by mauiflipper** [comment]
I did some more testing of the PHP service and I duplicated your example exactly.  If either of these two conditions are met, the service returns "null", as the entirety of the reply:

1.) If the total initial found records are zero.
2.) if the listOffset parameter exceeds the found total.

So if this is my request to the service:
www.domain.com/services/getproperties_tablet_test2.php?Class=Residential&listomatic[perPage]=10&listomatic[listOffset]=0

If the total found records for that query were equal to 30 and the list listOffset parameter sent from the plugin was 31, then it will return null. This instance only happens when a user gets to the end of the list and then clicks the Show more button one last time. 

The two conditions above are related.  I think the plugin is working fine and the PHP service is not functioning properly.

**Comment by mauiflipper** [comment]
The Service on your server has the same issue:

http://www.stakbit.com/listomatic/numbers.php?listomatic%5BperPage%5D=1&listomatic%5BlistOffset%5D=1600

Also, if you go to: http://listomatic.stakbit.com
and type in "fubar" into the Search field, you will see this error in your javascript:
6listomatic.stakbit.com:174TypeError: 'null' is not an object (evaluating 'data.numbers')

It's all related to the same problem with the php script.

**Comment by mauiflipper** [comment]
OK, I made some changes in the PHP service and javascript that fixes the errors and the show more button will not load of there are no found records (on the initial search):

I moved this line: 
$aData['total'] = $iFoundRows;

to above this line: 
while($row = mysqli_fetch_array($result)) {

and also added this new line: $aData['items'] = '';
as the next line.

In the javascript (line 13):
I changed this line:
 if (data.numbers) {
to this:
 if (data.total > 0) {

However, if there are 10 records, once all ten records are displayed, the Show more Button still shows, if you used that button to get there.  But if the initial load, included all 10 records, then the button will not show.

**Comment by stakbit** [comment]
I updated the plugin to deal with the null returned from the server.  Give it a try here: http://listomatic.stakbit.com/

Enter 'fubar' and you will see a "No Results Found" (this text is configurable):

First download and install the latest version of the plugin: https://github.com/stakbit/jQuery-Mobile-Listview-Pagination-Plugin/blob/master/jquery.mobile.listomatic.js

Now in your Ajax call change the following: 

From:

<pre>
success: function(data) {
if (data.numbers) {
</pre>

To:

<pre>
success: function(data) {
if (data && data.numbers) {
</pre>
                

You can see the full example at: https://github.com/stakbit/jQuery-Mobile-Listview-Pagination-Plugin#register-an-ajax-function              

Now when you do a Search and no results are found you will get a "No Results Found" message (instead of getting the Javascript error). You can change this message by changing the "noResultsFound" option: 
https://github.com/stakbit/jQuery-Mobile-Listview-Pagination-Plugin#configuration

There are no changes to be done on the server side.

**Comment by mauiflipper** [comment]
OK, that fixed the first error, but not the second error.  If the user continues to click the Show More button until they get to the end, they get both the 'Show More' button and the 'No Results Found' message.  

Go to: http://listomatic.stakbit.com
and type "2009" in the search field.

I am thinking you are going to have to modify the PHP service to make this work right.

**Comment by stakbit** [comment]
I am not seeing the problem on http://listomatic.stakbit.com . Can you replicate the problem on http://listomatic.stakbit.com and let me know the exact steps that were taken to get the "Show More" and "No Results Found" button at the same time? 

If you are still experiencing the issue on your end, I suspect its your server side code that is not setup correctly. Can you post your code for review.

**Comment by mauiflipper** [comment]
Type "2007" into the search field. 

Daryl

**Comment by stakbit** [comment]
I tried 2007 on http://listomatic.stakbit.com/ and still no go. I am wondering if this is a cache issue on the browser. Can you clear the browser cache and try again.

**Comment by mauiflipper** [comment]
I see it happening in Safari, Chrome & Firefox. I get both buttons.

Here's what I see on your site: 

And on my site:

On my site, I have to click the "Show More" button to get to the end to see both buttons. 
http://www.mauirealestate.net/tablet/SearchResultsMaui.html?Class=Residential&WaterFront%5B%5D=BeachFront&WaterFront%5B%5D=OceanFront

These are very similar, except your site has two records between the two buttons.

Daryl

**Comment by stakbit** [comment]
The problem was with the plugin trying to find the #listview selector in your list view's ul, when in your code it's #employeeList . It was never counting the displayed records, thus continued to show the "Show More" button after all the items were retrieved, then when you clicked on the last "Show More" button it returned a null and the plugin was not built to response to that since it should have never gotten that far.

Download and install v0.5.3: https://github.com/stakbit/jQuery-Mobile-Listview-Pagination-Plugin/blob/master/jquery.mobile.listomatic.js

**Comment by mauiflipper** [comment]
She's alive!

**Comment by mauiflipper** [comment]
Hi Jose,

It seems to work flawlessly now.  I wonder if you have a little time to help me find and fix a couple of bugs in my search results?  I can't seem to figure these out and I am betting you could pretty easily.  

Two items I noticed on my site: 
http://www.mauirealestate.net/tablet/SearchResultsMaui.html?Class=Residential&WaterFront%5B%5D=BeachFront&WaterFront%5B%5D=OceanFront

1.) If I click on a property in the list view to go to the details page, after clicking on the "Show More" button (on one of the newly aded properties), the details page is not loaded with ajax.   

2.) If I switch between Grid View & List View after clicking on the "Show More" button, only the added list view items are shown on the resulting page.  

Let me know if you can help and what you charge. We don't have any time deadlines, so when whenever is just fine.

Thanks,

Daryl Hansen

**Comment by stakbit** [comment]
The problem is that the plugin was developed to attach to only one listview per project (never had the need to use multiple listviews).  Using it on another listview with jquery mobile's single page model will confuse the plugin since they will share the same ajax function, offsets, options, selectors - this is definitely not desirable since each listview should be independent of each other.

There are a few options that I can think of to help you:
1. Do not apply the plugin to the listview on the grid view, just show all records for this page. (this is the quickest fix)
2. When a click to the grid view button is performed, do a whole page refresh (this kind of sucks since you will loose the transition effect). (this is the second quickest fix)
3. Wait until I (or someone else) updates the plugin to support multiple listviews each with its own registered ajax function, offsets, options, selectors, etc. (this one will take the longest - I opened a ticket for this https://github.com/stakbit/jQuery-Mobile-Listview-Pagination-Plugin/issues/5).

**Comment by mauiflipper** [comment]
I like Option #2 for now.  I don;t think people will be flipping back and forth much.  It is more of  a preference, that will be saved so that can always get their search results the way they want.  Thank you.  Do you have any ideas why this is happening?:

If I click on a property in the list view to go to the details page, after clicking on the "Show More" button (on one of the newly aded properties), the details page is not loaded with ajax.   

Daryl

**Comment by mauiflipper** [comment]
Hi Jose,

Do you have a time frame to make it compatible with JQM 1.4?

Daryl
